# Generated by Django 2.0.12 on 2020-04-19 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=500)),
                ('reviewer', models.CharField(max_length=500)),
                ('review', models.CharField(default=2, max_length=500)),
                ('reviewer_image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
