# Generated by Django 2.0.12 on 2020-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='post',
            field=models.CharField(default=2, max_length=500),
        ),
    ]
