# Generated by Django 2.0.12 on 2020-05-01 16:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skills',
            name='skill_percent',
            field=models.ForeignKey(default=2, max_length=300, on_delete=django.db.models.deletion.CASCADE, to='resume.Percent'),
        ),
        migrations.AlterField(
            model_name='education',
            name='year',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='skills',
            name='skill',
            field=models.CharField(max_length=250),
        ),
    ]
