# Generated by Django 2.0.12 on 2020-05-02 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0004_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='images',
        ),
        migrations.AddField(
            model_name='certificate',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
